[package]
name = "opcode-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift-codegen = { path = "../wasmtime/cranelift/codegen" }
itertools = "0.10.3"
